WITH 

INSTALACIONES2021 AS(
  SELECT
    DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS NOMBRE_CONTRATO,FECHA_APERTURA as FechaApertura,FECHA_FINALIZACION as FechaInst,NO_ORDEN
  FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D`
  WHERE
    EXTRACT(year FROM FECHA_APERTURA) = 2021 AND TIPO_ORDEN ="INSTALACION"
    AND MOTIVO_ORDEN = "INSTALACION-Orden de servicio" AND ESTADO = "FINALIZADA" AND FECHA_APERTURA IS NOT NULL AND FECHA_FINALIZACION IS NOT NULL
  GROUP BY
    NO_ORDEN, NOMBRE_CONTRATO,FECHA_APERTURA,FECHA_FINALIZACION ),

CHURNERSSO AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',c.NOMBRE_CONTRATO) ,10) AS CONTRATOSO, FECHA_APERTURA
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` c 
 INNER JOIN INSTALACIONES2021 i on RIGHT(CONCAT('0000000000',c.NOMBRE_CONTRATO) ,10) = i.NOMBRE_CONTRATO
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
 AND FECHA_APERTURA IS NOT NULL
 AND c.FECHA_APERTURA > i.FechaInst AND DATE_DIFF (c.FECHA_APERTURA, i.FechaInst, DAY) <= 90
 ORDER BY CONTRATOSO),

CHURNERSCRM AS
( SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOCRM,  MAX(CST_CHRN_DT) AS Maxfecha
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
 GROUP BY CONTRATOCRM
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION)) ),

CRUCECHURNERS AS(
SELECT CONTRATOSO, CONTRATOCRM, FECHA_APERTURA
FROM CHURNERSCRM c LEFT JOIN CHURNERSSO s ON CONTRATOSO = CONTRATOCRM 
AND c.Maxfecha >= s.FECHA_APERTURA AND date_diff(c.Maxfecha, s.FECHA_APERTURA, MONTH) <= 3
GROUP BY contratoso, contratoCRM, FECHA_APERTURA),


ALTAS AS (
  SELECT DISTINCT RIGHT(CONCAT('0000000000',CONTRATO) ,10) AS Contrato, MAX(Formato_Fecha) AS fecha
  FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-20_CR_ALTAS_V3_2021-01_A_2021-12_T`
  WHERE
  Tipo_Venta="Nueva"
  AND (Tipo_Cliente = "PROGRAMA HOGARES CONECTADOS" OR Tipo_Cliente="RESIDENCIAL" OR Tipo_Cliente="EMPLEADO")
  AND extract(year from Formato_Fecha) = 2021 
  AND Subcanal__Venta<>"OUTBOUND PYMES" AND Subcanal__Venta<>"INBOUND PYMES" AND Subcanal__Venta<>"HOTELERO" AND Subcanal__Venta<>"PYMES – NETCOM" 
  AND Tipo_Movimiento= "Altas por venta"
  GROUP BY contrato ),

TIEMPOINSTALACIONCONTRATOS AS(
    SELECT DISTINCT i.NOMBRE_CONTRATO as CONTRATO, EXTRACT (MONTH FROM i.FechaInst) AS MES, DATE_DIFF (i.FechaInst, i.FechaApertura, DAY) AS TIEMPOINST
    FROM INSTALACIONES2021 i INNER JOIN ALTAS a ON i.NOMBRE_CONTRATO = a.CONTRATO
    WHERE a.fecha>=i.FechaInst AND date_diff(i.fechainst, a.fecha, day)<=30
    GROUP BY CONTRATO, MES, TIEMPOINST
),

TIEMPOINSTALACIONCHURNERS AS(
  SELECT DISTINCT i.NOMBRE_CONTRATO as CONTRATO, EXTRACT (MONTH FROM i.FechaInst) AS MES, DATE_DIFF (i.FechaInst, i.FechaApertura, DAY) AS TIEMPOINSTCHURN
    FROM INSTALACIONES2021 i INNER JOIN ALTAS a ON i.NOMBRE_CONTRATO = a.CONTRATO INNER JOIN CRUCECHURNERS c on i.NOMBRE_CONTRATO = c.CONTRATOSO
    WHERE c.FECHA_APERTURA > i.FechaInst AND DATE_DIFF(c.FECHA_APERTURA, i.FechaInst, DAY) <= 60
    AND a.fecha>=i.FechaInst AND date_diff(i.fechainst, a.fecha, day)<=30
    GROUP BY CONTRATO, MES, TIEMPOINSTCHURN
),

TIERSTIEMPOSCONTRATOS AS(
  SELECT MES,
  CASE WHEN TIEMPOINST <= 2 THEN "0 A 2"
   WHEN TIEMPOINST>2 AND TIEMPOINST<=4 THEN "2 a 4"
  WHEN TIEMPOINST>4 AND TIEMPOINST<=6 THEN "4 a 6" 
  WHEN TIEMPOINST>6 AND TIEMPOINST<=8 THEN "6 a 8" 
  WHEN TIEMPOINST>8 AND TIEMPOINST<=10 THEN "8 a 10" 
  WHEN TIEMPOINST>10 AND TIEMPOINST<=12 THEN "10 a 12" 
  WHEN TIEMPOINST>12 AND TIEMPOINST<=14 THEN "12 a 14" 
  WHEN TIEMPOINST>14 THEN ">14"
  END AS TIERTIEMPOS, COUNT(DISTINCT CONTRATO) AS NUMCONTRATOS
  FROM TIEMPOINSTALACIONCONTRATOS
  GROUP BY TIERTIEMPOS,MES
),

TIERSTEMPOSCHURNERS AS(
  SELECT MES,
  CASE WHEN TIEMPOINSTCHURN <= 2 THEN "0 A 2"
  WHEN TIEMPOINSTCHURN>2 AND TIEMPOINSTCHURN<=4 THEN "2 a 4"
  WHEN TIEMPOINSTCHURN>4 AND TIEMPOINSTCHURN<=6 THEN "4 a 6" 
  WHEN TIEMPOINSTCHURN>6 AND TIEMPOINSTCHURN<=8 THEN "6 a 8" 
  WHEN TIEMPOINSTCHURN>8 AND TIEMPOINSTCHURN<=10 THEN "8 a 10" 
  WHEN TIEMPOINSTCHURN>10 AND TIEMPOINSTCHURN<=12 THEN "10 a 12" 
  WHEN TIEMPOINSTCHURN>12 AND TIEMPOINSTCHURN<=14 THEN "12 a 14" 
  WHEN TIEMPOINSTCHURN>14 THEN ">14"
  END AS TIERTIEMPOSCHURNERS, COUNT(DISTINCT CONTRATO) AS NUMCHURNERS
  FROM TIEMPOINSTALACIONCHURNERS
  GROUP BY TIERTIEMPOSCHURNERS,MES
)

SELECT tt.MES as Mes, tt.TIERTIEMPOS AS TierTiempos, NUMCONTRATOS as NumContratos, NUMCHURNERS as Churners, ROUND (NUMCHURNERS/NUMCONTRATOS,4) as ChurnRate
FROM TIERSTIEMPOSCONTRATOS tt LEFT JOIN TIERSTEMPOSCHURNERS tc ON tt.MES = tc.MES AND tt.TIERTIEMPOS = tc.TIERTIEMPOSCHURNERS
ORDER BY Mes, CASE WHEN TierTiempos = "0 A 2" THEN 1
WHEN TierTiempos ="2 a 4" THEN 2
WHEN TierTiempos ="4 a 6" THEN 3
WHEN TierTiempos ="6 a 8" THEN 4
WHEN TierTiempos ="8 a 10" THEN 5
WHEN TierTiempos ="10 a 12" THEN 6
WHEN TierTiempos ="12 a 14" THEN 7
WHEN TierTiempos = ">14" THEN 8 END
